apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: lb-space
      protocol: layer2
      addresses:
      - 192.168.120.230-192.168.120.250
