apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app
  namespace: ns-nginx-hello-app
  labels:
    app: hello-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-app
  template:
    metadata:
      labels:
        app: hello-app
    spec:
      containers:
      - image: nginxdemos/hello
        name: hello-app
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: ns-nginx-hello-app
  labels:
    app: hello-app
spec:
  type: ClusterIP
  selector:
    app: hello-app
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-hello-app-ingress
  namespace: ns-nginx-hello-app
  annotations:
    kubernetes.io/ingress.class: nginx
    # ingress.kubernetes.io/ssl-passthrough: "true"
    # nginx.ingress.kubernetes.io/secure-backends: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
    - hosts:
      - c1-nginx-hello-app.flexlab.local
      secretName: nginx-hello-app-tls
  rules:
  - host: c1-nginx-hello-app.flexlab.local
    http:
      paths:
      - path: /
        backend:
          serviceName: nginx-service
          servicePort: 80
