apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-pvc-01
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi 
  volumeName: static-pv-01    
  storageClassName: vsphere-static
